### ISSUE TITLE
make use of time.clock_gettime_ns() 

### ISSUE THREAD

**Issue by socketpair** [mdomke/python-ulid#12]
It is faster and without floating point. Just `time.clock_gettime_ns()  // 1000000` to get milliseconds.

**Comment by mdomke** [comment]
@socketpair Feel free to create a pull-request 😄

**Comment by musicinmybrain** [comment]
This is a good idea. I’m not sure if it’s really meaningfully faster, but it does make sense to use an integer API when we want an integer. One caveat is that [`clock_gettime_ns`](https://docs.python.org/3/library/time.html#time.clock_gettime_ns) is UNIX-only, while [`time_ns`](https://docs.python.org/3/library/time.html#time.time_ns) is portable, and should be just as good except that the former has the ability to specify a [non-default clock](https://docs.python.org/3/library/time.html#time-clock-id-constants). I’ll submit a PR to change the default-initialization method as suggested here.

**Comment by socketpair** [comment]
IS fater: https://github.com/python/cpython/issues/111482
