### ISSUE TITLE
PyPI page doesn't link back to GitHub

### ISSUE THREAD

**Issue by simonw** [mdomke/python-ulid#18]
https://pypi.org/project/python-ulid/#description currently:

![CleanShot 2024-03-27 at 21 55 40@2x](https://github.com/mdomke/python-ulid/assets/9599/05b87510-9a7e-4700-aa5c-0ba6ab9b1128)

No links back to GitHub, I had to Google to find the source code.

**Comment by mdomke** [comment]
Thanks! Proper links are now available on PyPI
