### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by ljnsn** [mdomke/python-ulid#6]
Is this library maintained? Should we switch to another python ULID library? [This PR](https://github.com/mdomke/python-ulid/pulls) has been open for almost a year without any feedback.

I'd be willing help out with maintaining this.

**Comment by mdomke** [comment]
Hi @ljnsn thanks for the heads-up. The PR about adding the `__hash__`-method must have slipped through. I incorporated it together with other changes into the new release 2.0.

**Comment by mdomke** [comment]
By the way: Support is always welcome!

**Comment by johnpaulett** [comment]
Thanks for the new release!  The`__hash__` fix let me remove a subclass I used to wrap ULID.
